use_default_settings: true

general:
  instance_name: "SearXNG"

server:
  secret_key: "REPLACE_ME_WITH_A_SECRET_KEY"
  limiter: false

search:
  safe_search: 1
  formats:
    - html
    - json

engines:
  - name: google
    engine: google
    shortcut: g

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg

  - name: qwant
    engine: qwant
    shortcut: qw

  - name: wikipedia
    engine: wikipedia
    shortcut: wp

  - name: dbpedia
    engine: dbpedia
    shortcut: db
